#!/bin/sh
# Regenerates Shared/ShareExtension/SafariExt.js, the share extensions' JavaScript
# preprocessing file, from the Readability.js and DOMPurify copies the app uses
# (Modules/Extraction/Sources/Extraction/JavaScript). Run it after updating those.
set -eu
cd "$(dirname "$0")/.."
js=Modules/Extraction/Sources/Extraction/JavaScript
out=Shared/ShareExtension/SafariExt.js
{
	cat <<'HEADER'
// Generated by buildscripts/make_safari_ext_js.sh. Don't edit; edit the script.
//
// Safari runs this in the page being shared. It returns the page's address and
// title and, when Readability finds an article, its sanitized body, so pages that
// need the user's sign-in are saved as the user sees them. Everything is wrapped
// so nothing is added to the page's globals.

var NetNewsListCapture = (function () {
	var module = { exports: {} };
	var exports = module.exports;
HEADER
	cat "$js/Readability.js"
	printf '\n\tvar ReadabilityClass = module.exports;\n\tmodule = { exports: {} };\n\texports = module.exports;\n'
	cat "$js/purify.min.js"
	cat <<'FOOTER'

	var purify = module.exports;
	var maximumBodyLength = 400000;
	var minimumTextLength = 100;

	return function () {
		var result = { url: document.URL, title: document.title };
		try {
			var article = new ReadabilityClass(document.cloneNode(true)).parse();
			if (article && article.content && (article.length || 0) >= minimumTextLength) {
				var body = purify.sanitize(article.content, {
					FORBID_TAGS: ["style", "form", "input", "button", "textarea", "select", "dialog"],
					FORBID_ATTR: ["style"]
				});
				if (body.length <= maximumBodyLength) {
					result.body = body;
				}
				if (article.title) {
					result.title = article.title;
				}
			}
		} catch (error) {
			// The app fetches and extracts the page itself.
		}
		return result;
	};
})();

var SafariExtPreprocessorClass = function() {};

SafariExtPreprocessorClass.prototype = {
	run: function(parameters) {
		parameters.completionFunction(NetNewsListCapture());
	}
};

// The JavaScript file must contain a global object named "ExtensionPreprocessingJS".
var ExtensionPreprocessingJS = new SafariExtPreprocessorClass;
FOOTER
} > "$out"
echo "Wrote $out"
